# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e045e04ef14c83f7cfa9c15954adf6423429e4c2b9bba6cb2dc24089dabe6193b7568ab669d28fd3cdaf049eb4416529fe95c472583cfcf9f1601913a76b4462

test:
  secret_key_base: 81a6257b70af692e876e82bbe97c4a4d0f5c7e27468f858090031cf5a292dde251ccfb7dd5e18c27dcf2ad155f7de25e04d85217bd18cec17a91ca37989be02b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
